apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: metallb
  contents:
  - path: .
    git:
      url: https://github.com/alexandreroman/metallb-tanzu-extra.git
      ref: f11f98450b04393a9b91955f74ffb6d74a6ee0ca
    includePaths:
    - metadata.yaml
    - 0.10.3/package.yaml
    - 0.11.0/package.yaml
- path: kube-vip
  contents:
  - path: .
    git:
      url: https://github.com/alexandreroman/kube-vip-tanzu-extra.git
      ref: adfff3321d479b6eaa47c5b0ef20c5c2adc61cd1
    includePaths:
    - metadata.yaml
    - 0.3.9/package.yaml
